ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('customer/', include('customer.urls')),
    path('owner/', include('owner.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

owner/urls.py
from django.urls import path
from .views import *
app_name = 'owner'
urlpatterns = [
    path('admin-home/', AdminHomeView.as_view(), name="admin_home"),
    path('admin-login/', AdminLoginView.as_view(), name="admin_login"),
    path('admin-order/<int:pk>/', AdminOrderDetailView.as_view(), name="admin_order_detail"),
    
    path('admin-all-orders/', AdminOrderListView.as_view(), name="admin_order_list"),
    path('admin-order-<int:pk>-change', AdminOrderStatusChangeView.as_view(), name="admin_order_status_change"),
    
]

shop/urls.py
from django.urls import path
from .views import *
app_name = 'shop'
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('all-product/', AllProductView.as_view(), name="all_product"),
    path('about/', AboutView.as_view(), name="about"),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name="product_detail"),
    
    path('add-to-cart-<int:pro_id>', AddToCartView.as_view(), name="add_to_cart"),
    path('mycart/', MyCartView.as_view(), name="my_cart"),
    path('manage-cart/<int:cp_id>', ManageCartView.as_view(), name="manage_cart"),
    path('empty-cart/', EmptyCartView.as_view(), name="empty_cart"),
     
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('search/', SearchView.as_view(), name="search" ),
    
    path('esewa-request/', EsewaRequestView.as_view(), name="esewa_request"),
    path('esewa-verify/', EsewaVerifyView.as_view(), name="esewa_verify"),
    # path('search/', SearchView.as_view(), name="search" ),
    
    
    
    
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)
    
    def __str__(self):
        return self.user.username
    


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.full_name
    
    
    
    
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    
    def __str__(self):
        return self.title
    
class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    image= models.ImageField(upload_to='products')
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.title
    

class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL,  null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveBigIntegerField()
    subtotal = models.PositiveIntegerField()
    
    def __str__(self):
        return "Cart" + str(self.cart.id) + "CartProduct" + str(self.id)
    
    

ORDER_STATUS=(
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),    
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/adminpages/admin_base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock%}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container pt-3">
            <div class="row">

                <a href="{% url 'owner:admin_home' %}">Admin Home  </a>  |
                <a href="{% url 'owner:admin_order_list' %}">All Order  </a>  |
                <a href="{% url 'shop:home' %}" target="blank">Vist Site  </a>  |
            </div>
        </div>
        
        {% block content %}
        {% endblock %}
        <script src="" async defer></script>
    </body>
</html>

templates/adminpages/admin_home.html
{% extends 'adminpages/admin_base.html' %}

{% block title %}Admin{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h2>Pending Orders</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>SN.</th>
                        <th>ORDER ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in pending_orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'owner:admin_order_detail' i.id%}">#ORDER{{i.id}}</td>
                        <td>{{i.ordered_by}}</td>
                        <td>{{i.created_at}}</td>
                        <td>{{i.total}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

    

</div>
{% endblock %}

templates/adminpages/admin_login.html
{% extends 'base.html' %}

{% block title %}Admin Login{% endblock %}

{% block content %}


<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3 class='font-weight-bold'>Admin Login Form</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Login as a Admin</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
            
        </div>
    </div>
</div>
{% endblock %}

templates/adminpages/admin_orderdetail.html
{% extends 'adminpages/admin_base.html' %}
{% load humanize %}

{% block title %}Order Detail {% endblock %}

{% block content %}

<div class="containter">
    <div class="row">
    
        <div class="col-md-9 mx-auto">
            <h3>Order Detail</h3>
            <p><span class="font-weight-bold">Order ID: </span> #ORDER{{ord_obj.id}} </p>
            <p><span class="font-weight-bold">Order STATUS: </span> {{ord_obj.order_status}} </p>
            <p><span class="font-weight-bold">Order CREATED AT: </span> {{ord_obj.created_at}} {{ord_obj.created_at|timesince}} ago</p>
            <p><span class="font-weight-bold">SHIPPING INFORMATION: </span> 
                <ul>
                <li> ordered by:{{ord_obj.ordered_by}}</li>
                <li> address:{{ord_obj.shipping_address}} </li>
                <li> email:{{ord_obj.email}}</li> 
                <li> mobile:{{ord_obj.mobile}}</li>
                </ul>
            </p>
            <p><span class="font-weight-bold">PAYMENT INFO: </span> {{ord_obj.payment_method}}({{ord_obj.payment_completed}}) </p>
            <hr>

            <table class="table">
                <thead>
                    <tr>
                        <th>SN.</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity.</th>
                        <th>subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}} {{cp.product.id}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total:</th>
                        <th>Rs. {{ord_obj.total|intcomma}}/-</th>
                </tbody>
                <form action="{% url 'owner:admin_order_status_change' ord_obj.id %}" method="POST">
                    {% csrf_token %}
                    <select name="status">
                        {% for i,j in allstatus %}
                        <option value="{{i}}" {% if i == ord_obj.order_status%} selected {% endif %} >{{j}}</option>
                        {% endfor %}
                    </select>
                    <button class="btn btn-info">Change</button>
                         



                </form>
            </table>
        </div>
    </div>
</div>


{% endblock %}

templates/adminpages/admin_orderlist.html
{% extends 'adminpages/admin_base.html'%}

{% block title%}All Orders{% endblock %}
{% block content%}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h2>Orders</h2>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>SN.</th>
                        <th>ORDER ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in ord_obj %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'owner:admin_order_detail' i.id%}">#ORDER{{i.id}}</td>
                        <td>{{i.ordered_by}}</td>
                        <td>{{i.created_at}}</td>
                        <td>{{i.total}}</td>
                        <td>{{i.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

    

</div>
{% endblock %}