customer/urls.py
from django.urls import path
from .views import *
app_name = 'customer'
urlpatterns = [
    path('customer-registration/', CustomerRegistrationView.as_view(), name="customer_registration"),
    path('customer-logout/', CustomerLogoutView.as_view(), name="customer_logout"),
    path('customer-login/', CustomerLoginView.as_view(), name="customer_login"),
    
    path('customer-profile/',CustomerProfileView.as_view(), name="customer_profile"),
    path('customer-profile/order-<int:pk>',OrderDetailsView.as_view(), name="order_details"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('customer/', include('customer.urls')),
    path('owner/', include('owner.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

owner/urls.py
from django.urls import path
from .views import *
app_name = 'owner'
urlpatterns = [
    path('admin-home/', AdminHomeView.as_view(), name="admin_home"),
    path('admin-login/', AdminLoginView.as_view(), name="admin_login"),
    path('admin-order/<int:pk>/', AdminOrderDetailView.as_view(), name="admin_order_detail"),
    
    path('admin-all-orders/', AdminOrderListView.as_view(), name="admin_order_list"),
    path('admin-order-<int:pk>-change', AdminOrderStatusChangeView.as_view(), name="admin_order_status_change"),
    
]

shop/urls.py
from django.urls import path
from .views import *
app_name = 'shop'
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('all-product/', AllProductView.as_view(), name="all_product"),
    path('about/', AboutView.as_view(), name="about"),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name="product_detail"),
    
    path('add-to-cart-<int:pro_id>', AddToCartView.as_view(), name="add_to_cart"),
    path('mycart/', MyCartView.as_view(), name="my_cart"),
    path('manage-cart/<int:cp_id>', ManageCartView.as_view(), name="manage_cart"),
    path('empty-cart/', EmptyCartView.as_view(), name="empty_cart"),
     
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('search/', SearchView.as_view(), name="search" ),
    
    path('esewa-request/', EsewaRequestView.as_view(), name="esewa_request"),
    path('esewa-verify/', EsewaVerifyView.as_view(), name="esewa_verify"),
    # path('search/', SearchView.as_view(), name="search" ),
    
    
    
    
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)
    
    def __str__(self):
        return self.user.username
    


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.full_name
    
    
    
    
class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    
    def __str__(self):
        return self.title
    
class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    image= models.ImageField(upload_to='products')
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warranty = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.title
    

class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL,  null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveBigIntegerField()
    subtotal = models.PositiveIntegerField()
    
    def __str__(self):
        return "Cart" + str(self.cart.id) + "CartProduct" + str(self.id)
    
    

ORDER_STATUS=(
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),    
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Khalti", "Khalti"),
    ("Esewa", "Esewa"),
)

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<div class="container mt-4">
    
    <h1 class="text-center font-weight-bold">Welcome to our ecommerce website about. </h1>
    <hr>
    

</div>
{% endblock %}

templates/all_product.html
{% extends 'base.html' %}

{% block title %}All Product{% endblock %}

{% block content %}
<div class="container mt-4">
    
    <h1 class="text-center font-weight-bold">All Products according to Category </h1>
    
    <hr>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Success!</strong> {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div> 
        {% endfor %}
    </ul>
    {% endif %}

    <div class="container mt-2">
        <div class="row ">
            <div class="col-md-4">

                <div class="pagination">
                    <span class="step-links">
                        {% if category_list.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ category_list.previous_page_number }}">previous</a>
                        {% endif %}
                
                        <span class="current">
                            Page {{ category_list.number }} of {{ category_list.paginator.num_pages }}.
                        </span>
                
                        {% if category_list.has_next %}
                            <a href="?page={{ category_list.next_page_number }}">next</a>
                            <a href="?page={{ category_list.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>

    {% for cat in category_list%}
    
    <h1 class="text-info text-center">{{ cat.title }}</h1>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-4 mt-2 card" >
            <div class="md-3">
                <h3><a href="{% url 'shop:product_detail' p.slug %}">{{ p.title }}</h3>
                <img src="{{ p.image.url }}"  class="img-fluid">
                <br>
                <p class="mt-2">Price: <strike>Rs. {{p.marked_price}}</strike> Rs. {{p.selling_price}}</p>
                <a href="{% url 'shop:add_to_cart' p.id %}" class="btn btn-primary"> Add to cart</a>
            </div>    
        </div>
        {% endfor %}
    </div>
    <br>
    <hr >
    {% endfor %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="{% url 'shop:home'%}">E-Store & Accessories</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'shop:home'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'shop:all_product'%}">Categories</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'shop:about'%}">About</a>
            </li>
            
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'shop:my_cart'%}">My Cart</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                    
                    <a class="dropdown-item" href="{% url 'customer:customer_profile' %}">Profile</a>  
                    <a class="dropdown-item" href="{% url 'customer:customer_logout' %}">Logout</a>  

                {% else %}
                    <a class="dropdown-item" href="{% url 'customer:customer_registration' %}">Customer Register</a>  
                    <a class="dropdown-item" href="{% url 'customer:customer_login' %}"> Customer Login </a>  
                    <a class="dropdown-item" href="{% url 'owner:admin_login'%}">Admin Login </a>  

                {% endif %}
              </div>
            </li>
            
            
          </ul>
          <form class="form-inline my-2 my-lg-0" action="{% url 'shop:search' %}" method="GET">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="keyword" required>
            <button class="btn btn-warning my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
    </nav>

   
    
    


    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>

</html>

templates/checkout.html
{% extends 'base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row mt-4">
        <div class="col-md-6">
            <h1 class="text-center font-weight-bold">Cart Items.... </h1>
            <button class="btn-grey"><a href="{% url 'shop:my_cart'%}">Update Cart</a></button>
            <table class ="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>Rs.{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>Rs.{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="4" class="text-right">Total</td>
                        <td>Rs. {{cart.total}}</td>
                </tbody>
            </table>
        
        </div>
        <div class="col-md-6">
            <h1 class="text-center font-weight-bold">Checkout Form </h1>
            <form action="" method="POST" class="mt-4">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-info">Place Order</button>
            </form>
        </div>
    </div>
</div>    
    
    
    
    

</div>
{% endblock %}

templates/customer_login.html
{% extends 'base.html' %}

{% block title %}Customer Login{% endblock %}

{% block content %}


<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3 class="font-weight-bold">Login Form</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Register as a Customer</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
            <p> No account ? <a href="{% url 'customer:customer_registration'%}{% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Register here</a></p>
        </div>
    </div>
</div>
{% endblock %}

templates/customer_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <h3 class="font-weight-bold">My Profile</h3>
            <hr>
            <p><span class="font-weight-bold">Name: </span> {{customer.full_name}} </p>
            <p><span class="font-weight-bold">Username: </span> {{customer.user.username}} </p>
            <p><span class="font-weight-bold">Email: </span> {{customer.user.email}} </p>
            <p><span class="font-weight-bold">Address: </span> {{customer.address}} </p>
            <p><span class="font-weight-bold">Joined On: </span> {{customer.joined_on}} </p>
        </div>
        <div class="col-md-6">
            <h3 class="font-weight-bold">Order histroy</h3>
            {% comment %} {% for order in orders %} {% endcomment %}
            <hr>
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>SN.</th>
                        <th class="w-25">Order ID</th>
                        <th>Amount</th>
                        <th>Ordered</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                    <tr>
                        <td><a href="{% url 'customer:order_details' ord.id%}">{{forloop.counter}}</a></td>
                        <td>#{{ord.id}}</td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.created_at}}</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
        

{% endblock %}

templates/customer_registration.html
{% extends 'base.html' %}

{% block title %}Customer Registration{% endblock %}

{% block content %}
<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3 class='font-weight-bold'>Customer Registration Form</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Register as a Customer</button>
            </form>
            <p> Already have an account? <a href="{% url 'customer:customer_login'%}">Login here</a></p>
        </div>
    </div>
</div>
{% endblock %}

templates/esewa_request.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <style>
            #myform{
                display : none;
            }
        </style>
    </head>
    <body>
        

        <form class="form" action="https://epay.esewa.com.np/api/epay/main/v2/form " method="POST" id="myform">
            <input type="text" id="amount" name="amount" value="{{order.total}}" type="hidden" required>
            <input type="text" id="tax_amount" name="tax_amount" value ="0" required>
            <input type="text" id="total_amount" name="total_amount" value="{{order.total}}" type="hidden" required>
            <input type="text" id="transaction_uuid" name="transaction_uuid" value="{{order.id}}" required>
            <input type="text" id="product_code" name="product_code" value ="EPAYTEST" required>
            <input type="text" id="product_service_charge" name="product_service_charge" value="0" required>
            <input type="text" id="product_delivery_charge" name="product_delivery_charge" value="0" required>
            <input type="text" id="success_url" name="success_url" value="https:localhost:8000/esewa-verify/" required>
            <input type="text" id="failure_url" name="failure_url" value="{{request.build_absolute_uri}}" required>
            <input value="Submit" type="submit">
        </form>

        <script>
            setTimeout(function(){
                document.getElementById("myform").submit()
            }, 500)
        </script>
           
    </body>
        
        
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container mt-4">

    <h1 class="text-center font-weight-bold">Welcome to our ecommerce website. </h1>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Success!</strong> {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div> 
        {% endfor %}
    </ul>
    {% endif %}

    
      <div class="pagination">
        <span class="step-links">
            {% if product_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ product_list.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ product_list.number }} of {{ product_list.paginator.num_pages }}.
            </span>
    
            {% if product_list.has_next %}
                <a href="?page={{ product_list.next_page_number }}">next</a>
                <a href="?page={{ product_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

    

    <div class="row mt-4 text-center">
        {% for p in product_list %}
        <div class="col-md-4 card">
            <div class="md-3">
                <h3><a href="{% url 'shop:product_detail' p.slug %}">{{ p.title }}</a></h3>
                <img src="{{ p.image.url }}"  class="img-fluid" style="height:200px; object-fit: contain;">
                <br>
                <p class="mt-2">Price: <strike>Rs. {{p.marked_price}}</strike> Rs. {{p.selling_price}}</p>
                <a href="{% url 'shop:add_to_cart' p.id %}" class="btn btn-primary"> Add to cart</a>
            </div>    
        </div>
        {% endfor %}
    </div>
    
    
</div>

{% endblock %}

templates/mycart.html
{% extends 'base.html' %}

{% block title %}My Cart{% endblock %}

{% block content %}
<div class="container mt-4">
    
    <div class="row ">
    
        <div class="col-md-12">
            <h1 class="text-center font-weight-bold"> Items in my cart </h1>
           
            <table class ="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>

                    </tr>

                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>Rs.{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>Rs.{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'shop:manage_cart' cp.id %}?action=inc" class="btn btn-primary">+</a>
                            <a href="{% url 'shop:manage_cart' cp.id %}?action=dec" class="btn btn-warning">-</a>
                            <a href="{% url 'shop:manage_cart' cp.id %}?action=rem" class="btn btn-danger">x</a>

                        </td>
                    </tr>
                    {% endfor %}
                    {% if cart.cartproduct_set%}
                    <tr>
                        <th colspan='4'class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all%}
                        <th><a href="{%url 'shop:empty_cart' %}" class="btn btn-dark">Emtpy Cart</a>
                         {% endif %}   


                    </tr>
                    <tr>
                        <th><a href="{% url 'shop:checkout'%}" class="btn btn-info">CheckOut</a></th>
                    </tr>
                    {% else %}
                    <h2><a href="{%url 'shop:home' %}">Add Items first</a></h2>
                    {% endif %}
                    
                </tbody>
            </table>


        </div>
    </div>

</div>





{% endblock %}

templates/orderdetails.html
{% extends 'base.html' %}
{% load humanize%}

{% block title %}Order Detail{% endblock %}

{% block content %}
<div class="container">
    
    <h1 class="text-center font-weight-bold">Order Detail </h1>
    <div class="row">
        <div class="col-md-9 mx-auto">
            <p><span class="font-weight-bold">Order ID: </span> #ORDER{{ord_obj.id}} </p>
            <p><span class="font-weight-bold">Order STATUS: </span> {{ord_obj.order_status}} </p>
            <p><span class="font-weight-bold">Order CREATED AT: </span> {{ord_obj.created_at}} ({{ord_obj.created_at|timesince}} ago)</p>
            <p><span class="font-weight-bold">SHIPPING INFORMATION: </span> 
                <ul>
                <li> ordered by:{{ord_obj.ordered_by}}</li>
                <li> address:{{ord_obj.shipping_address}} </li>
                <li> email:{{ord_obj.email}}</li> 
                <li> mobile:{{ord_obj.mobile}}</li>
                </ul>
            </p>
            <hr>

            <table class="table">
                <thead>
                    <tr>
                        <th>SN.</th>
                        <th>Item</th>
                        <th>Rate</th>
                        <th>Quantity.</th>
                        <th>subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in ord_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}} {{cp.product.id}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total:</th>
                        <th>Rs. {{ord_obj.total|intcomma}}/-</th>
                </tbody>
            </table>
                    
        </div>
    </div>
</div>
 
    

</div>
{% endblock %}

templates/product_detail.html
{% extends 'base.html' %}

{% block title %}{{product.title}}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 font-weight-bold>Product name:{{ product.title }}</h2>

    {% if messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {% for message in messages%}
            <strong>Success!</strong> {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        {% endfor %}
          </div> 
    {% endif %}
    <div class="row mt-4"> 
        <div class="col-md-6" >
            <img src="{{ product.image.url }}"  class="img-fluid">
        </div>
        <div class="col-md-6" >
            <h3>{{ product.title }}     [view {{product.view_count}}]</h3>
            <h4>Category:{{product.category}}</h4>
            <p>Description: {{product.description}}<p>
            <p class="text-info">Warranty: {{product.warranty}}<p>
            <p class="text-info">Retrun policy: {{product.return_policy}}<p>
            <p class="mt-2">Price: <strike>Rs. {{product.marked_price}}</strike> Rs. {{product.selling_price}}</p>
            <a href="{% url 'shop:add_to_cart' product.id %}" class="btn btn-primary"> Add to cart</a>
        </div>        
    </div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% block content %}
<div class="container">
    <h2 font-weight-bold>Searched products:</h2>
    <hr>
    {%for product in product %}
    <div class="row mt-4 text-center">    
        <div class="col-md-6" >
            <img src="{{ product.image.url }}"  class="img-fluid" width="200">
        </div>
        <div class="col-md-6" >
            <h3><a href="{% url 'shop:product_detail' product.slug %}">{{ product.title }}</a>  
        </div>
    </div>  
    {% endfor %}

</div>
{% endblock %}